/**
 * Generates static translations of all UI labels for every supported language.
 * Calls the local LM Studio OpenAI-compatible API once per language with all labels batched.
 *
 * Usage: node scripts/generate-labels.mjs
 * Output: src/lib/translatedLabels.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");

const LM_STUDIO_URL = process.env.LM_STUDIO_URL || "http://localhost:1234";
const MODEL = process.env.DEFAULT_MODEL || "google/translategemma-27b-it";
const DELIMITER = "\n---\n";

// Parse DEFAULT_LABELS from the source of truth (labels.ts)
const labelsFile = readFileSync(resolve(projectRoot, "src/lib/labels.ts"), "utf-8");
const labelMatches = [...labelsFile.matchAll(/"([^"]+)":\s*"([^"]+)"/g)];
const LABELS = Object.fromEntries(labelMatches.map(([, key, val]) => [key, val]));

// Read the language list from the source
const langFile = readFileSync(resolve(projectRoot, "src/lib/languages.ts"), "utf-8");
const langMatches = [...langFile.matchAll(/code:\s*"([^"]+)",\s*name:\s*"([^"]+)"/g)];
const languages = langMatches
  .map(([, code, name]) => ({ code, name }))
  .filter((l) => l.code !== "en");

const keys = Object.keys(LABELS);
const texts = Object.values(LABELS);
const combined = texts.join(DELIMITER);

async function translateForLanguage(lang) {
  const prompt = `You are a professional English (en) to ${lang.name} (${lang.code}) translator. Your goal is to accurately convey the meaning and nuances of the original English text while adhering to ${lang.name} grammar, vocabulary, and cultural sensitivities.
Produce only the ${lang.name} translation, without any additional explanations or commentary. Please translate the following English text into ${lang.name}:


${combined}`;

  const response = await fetch(`${LM_STUDIO_URL}/v1/chat/completions`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      model: MODEL,
      messages: [{ role: "user", content: prompt }],
      temperature: 0.1,
      max_tokens: 4096,
    }),
    signal: AbortSignal.timeout(300_000),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`${lang.code}: HTTP ${response.status} - ${err}`);
  }

  const result = await response.json();
  const content = result.choices?.[0]?.message?.content ?? "";
  const translations = content
    .trim()
    .split(DELIMITER)
    .map((s) => s.trim());

  // Build label map, falling back to English if delimiter parsing failed
  const map = {};
  keys.forEach((key, i) => {
    const t = translations[i]?.trim();
    if (t) map[key] = t;
  });

  return map;
}

async function main() {
  const results = {};
  let done = 0;

  for (const lang of languages) {
    process.stdout.write(`[${done + 1}/${languages.length}] ${lang.code} (${lang.name})... `);
    try {
      const map = await translateForLanguage(lang);
      const translated = Object.keys(map).length;
      if (translated === keys.length) {
        results[lang.code] = map;
        console.log(`OK (${translated}/${keys.length})`);
      } else {
        console.log(`PARTIAL (${translated}/${keys.length} — skipping)`);
      }
    } catch (err) {
      console.log(`FAILED: ${err.message}`);
    }
    done++;
  }

  // Generate TypeScript file
  const output = `// Auto-generated by scripts/generate-labels.mjs — do not edit manually.
// Re-run: node scripts/generate-labels.mjs

import type { Labels } from "./labels";

export const translatedLabels: Partial<Record<string, Labels>> = ${JSON.stringify(results, null, 2)};
`;

  const outPath = resolve(projectRoot, "src/lib/translatedLabels.ts");
  writeFileSync(outPath, output, "utf-8");
  console.log(`\nWrote ${Object.keys(results).length} locales to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
